spring:
  data:
    mongodb:
      authentication-database: admin
      username: admin
      password: pass1
      database: test
      port: 27017
      host: localhost
      auto-index-creation: true
